import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import { generatedTsPath } from "../src/persist/workspace.js";
import { parsePageModelDraft, type PageModelDraft } from "../src/schema/page-model.js";
import { emitTs, graphFromModel, writeGeneratedTs } from "../src/ts/emit.js";
import { surfaceClassName } from "../src/ts/graph.js";

function loadValidHome(): PageModelDraft {
  const path = fileURLToPath(new URL("../fixtures/models/valid-home.json", import.meta.url));
  return parsePageModelDraft(JSON.parse(readFileSync(path, "utf8")));
}

describe("emitTs", () => {
  it("emits a chainable page model from valid-home", () => {
    const model = loadValidHome();
    const ts = emitTs(model, []);
    const dialog = surfaceClassName("home", { id: "createDialog", kind: "dialog" });
    assert.match(ts, /^\/\*\* Generated by `clickmonkey emit`\. Do not edit\. \*\//);
    assert.match(ts, /brain: "test"/);
    assert.match(ts, /class HomePage extends SurfaceChain/);
    assert.match(ts, new RegExp(`openCreate\\(\\): ${dialog}`));
    assert.match(ts, /fill\(fields: \{ name\?: string \}\)/);
    assert.match(ts, /submit\(\)/);
    assert.doesNotMatch(ts, /unresolved/);
    assert.doesNotMatch(ts, /open-create/);
    assert.doesNotMatch(ts, /schemaVersion/);
    assert.doesNotMatch(ts, /testId/);
    assert.match(ts, /readonly home: HomePage/);
  });

  it("names page id app as AppPage so it does not collide with the facade", () => {
    const model = loadValidHome();
    const home = model.pages[0];
    assert.ok(home);
    home.id = "app";
    const ts = emitTs(model, []);
    assert.match(ts, /export class App \{/);
    assert.match(ts, /readonly app: AppPage/);
    assert.match(ts, /class AppPage extends SurfaceChain/);
    assert.equal([...ts.matchAll(/export class App\b/g)].length, 1);
  });

  it("omits drift and unresolved widgets", () => {
    const model = loadValidHome();
    const page = model.pages[0]?.surfaces[0];
    const dialog = model.pages[0]?.surfaces[1];
    assert.ok(page && dialog);
    page.actions.push(
      { id: "ghost", by: "testId", value: "ghost", status: "unresolved" },
      { id: "staleOpen", by: "testId", value: "stale", status: "drift" },
    );
    dialog.fields.push({
      id: "gone",
      required: false,
      type: "text",
      by: "testId",
      value: "gone",
      status: "unresolved",
    });
    dialog.actions.push({ id: "cancelOld", by: "testId", value: "cancel", status: "drift" });
    const graph = graphFromModel(model, []);
    const actionIds = graph.pages.flatMap((p) => p.surfaces.flatMap((s) => s.actions.map((a) => a.id)));
    const fieldIds = graph.pages.flatMap((p) => p.surfaces.flatMap((s) => s.fields.map((f) => f.id)));
    assert.deepEqual(actionIds, ["openCreate", "submit"]);
    assert.deepEqual(fieldIds, ["name"]);
    const ts = emitTs(model, []);
    assert.doesNotMatch(ts, /\bghost\b/);
    assert.doesNotMatch(ts, /staleOpen/);
    assert.doesNotMatch(ts, /\bgone\b/);
    assert.doesNotMatch(ts, /cancelOld/);
  });

  it("copies intro secret tokens into graph.intro unchanged", () => {
    const intro = ['fill page.password $CLICKMONKEY_PASSWORD'];
    const graph = graphFromModel(loadValidHome(), intro);
    assert.deepEqual(graph.intro, intro);
    const ts = emitTs(loadValidHome(), intro);
    assert.match(ts, /\$CLICKMONKEY_PASSWORD/);
    assert.equal(ts.includes("s3cret"), false);
  });

  it("mangles reserved page and widget names instead of dropping rooms", () => {
    const model = {
      schemaVersion: 1,
      app: "x",
      generation: 0,
      pages: [
        {
          id: "home",
          path: "/",
          params: [],
          ready: { by: "testId", value: "home" },
          surfaces: [
            {
              id: "page",
              kind: "page",
              fields: [],
              actions: [
                { id: "then", by: "testId", value: "then", status: "ok" },
                { id: "fill", by: "testId", value: "fill", status: "ok" },
                { id: "open-x", by: "testId", value: "open-x", status: "ok" },
                { id: "goNext", by: "testId", value: "go", status: "ok" },
              ],
            },
          ],
        },
        {
          id: "then",
          path: "/then",
          params: [],
          ready: { by: "testId", value: "then" },
          surfaces: [{ id: "page", kind: "page", fields: [], actions: [] }],
        },
      ],
    } as unknown as PageModelDraft;
    const graph = graphFromModel(model, []);
    assert.deepEqual(
      graph.pages.map((p) => p.id),
      ["home", "then"],
    );
    assert.deepEqual(graph.pages[0]?.surfaces[0]?.actions.map((a) => a.id), ["then", "fill", "open-x", "goNext"]);
    assert.throws(() => emitTs(model, []), /open-x/);
    const ok = structuredClone(model);
    const actions = ok.pages[0]?.surfaces[0]?.actions;
    assert.ok(actions);
    ok.pages[0]!.surfaces[0]!.actions = actions.filter((a) => a.id !== "open-x");
    const ts = emitTs(ok, []);
    assert.match(ts, /goNext\(\)/);
    assert.match(ts, /thenAction\(\)/);
    assert.match(ts, /fillAction\(\)/);
    assert.match(ts, /readonly thenPage:/);
    assert.match(ts, /class ThenPage extends SurfaceChain/);
    assert.doesNotMatch(ts, /readonly then:/);
    assert.doesNotMatch(ts, /\bthen\(\)/);
  });

  it("disambiguates mangled page properties when then and thenPage both exist", () => {
    const page = (id: string) => ({
      id,
      path: `/${id}`,
      params: [],
      ready: { by: "testId" as const, value: id },
      surfaces: [{ id: "page", kind: "page" as const, fields: [], actions: [] }],
    });
    const ts = emitTs(
      {
        schemaVersion: 1,
        app: "x",
        generation: 0,
        pages: [page("then"), page("thenPage")],
      } as unknown as PageModelDraft,
      [],
    );
    assert.match(ts, /readonly thenPage:/);
    assert.match(ts, /readonly thenPage2:/);
    assert.match(ts, /class ThenPage extends SurfaceChain/);
    assert.match(ts, /class ThenPagePage extends SurfaceChain/);
  });

  it("mangles expectVisible so it does not shadow SurfaceChain.expectVisible", () => {
    const model = loadValidHome();
    model.pages[0]!.surfaces[0]!.actions.push({
      id: "expectVisible",
      by: "testId",
      value: "expect-visible",
      status: "ok",
    });
    const ts = emitTs(model, []);
    assert.match(ts, /expectVisibleAction\(\)/);
    assert.doesNotMatch(ts, /expectVisible\(\)/);
  });

  it("mangles flush so it cannot override SurfaceChain internals", () => {
    const model = loadValidHome();
    model.pages[0]!.surfaces[0]!.actions.push({
      id: "flush",
      by: "testId",
      value: "flush",
      status: "ok",
    });
    const ts = emitTs(model, []);
    assert.match(ts, /flushAction\(\)/);
    assert.doesNotMatch(ts, /flush\(\)/);
  });
});

describe("writeGeneratedTs", () => {
  it("writes clickmonkey/ts/generated.ts under the leash dir", () => {
    const dir = mkdtempSync(join(tmpdir(), "cm-emit-"));
    const configPath = join(dir, "clickmonkey.json");
    const intro = ["open home"];
    const model = loadValidHome();
    const out = writeGeneratedTs(configPath, model, intro);
    assert.equal(out, generatedTsPath(configPath));
    assert.equal(out, join(dir, "clickmonkey", "ts", "generated.ts"));
    const written = readFileSync(out, "utf8");
    assert.equal(written, emitTs(model, intro));
    assert.ok(written.endsWith("\n"));
  });
});
