export const version = "2.0.0-alpha.0";
export * from "./schema/index.js";
export * from "./surveyor/ids.js";
export * from "./surveyor/merge.js";
export * from "./persist/config.js";
export * from "./persist/log.js";
export * from "./persist/finding.js";
export * from "./persist/run-id.js";
export * from "./persist/events.js";
export { withRun } from "./executor/session.js";
export type { RunHandle } from "./executor/session.js";
export { toPlaywrightLocator } from "./executor/locators.js";
export { liveValidate } from "./executor/live-validate.js";
export type { LiveFailure } from "./executor/live-validate.js";
export { resolveCount } from "./surveyor/resolve.js";
export { inspect, inspectAndSaveConfig } from "./surveyor/inspect.js";
export type { InspectResult, SurveyorContext } from "./surveyor/inspect.js";
export { createExecutor } from "./executor/run.js";
export type { AfterStep, RunState, StepResult } from "./executor/run.js";
export { buildView, formatView } from "./executor/view.js";
export { checkFence, pathPrefixMatch } from "./executor/fence.js";
export { resolveSecret, resolveSecretAsync, isSecretToken } from "./executor/secrets.js";
export { isPotentialWrite } from "./executor/write-policy.js";
